### ISSUE TITLE
WebOb-1.2b2 breaks Pylons 1.0

### ISSUE THREAD

**Issue by mfontenele** [Pylons/pylons#11]
When running paster I get the following error that does not occur with previous WebOb versions.

<pre>
$ paster serve production.ini
Traceback (most recent call last):
  File "/usr/local/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/usr/local/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/local/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/usr/local/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/usr/local/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/usr/local/lib/python2.5/site-packages/PasteScript-1.7.3-py2.5.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/usr/local/lib/python2.5/site-packages/PasteDeploy-1.5.0-py2.5.egg/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 1954, in load
  File "/usr/local/lib/python2.5/site-packages/mstery-0.0.0-py2.5.egg/mstery/config/middleware.py", line 25, in <module>
    from pylons.middleware import ErrorHandler, StatusCodeRedirect
  File "/usr/local/lib/python2.5/site-packages/Pylons-1.0-py2.5.egg/pylons/middleware.py", line 7, in <module>
    from weberror.evalexception import EvalException
  File "/usr/local/lib/python2.5/site-packages/WebError-0.10.3-py2.5.egg/weberror/evalexception.py", line 50, in <module>
    from webob import Request, Response
  File "/usr/local/lib/python2.5/site-packages/PIL-1.1.7-py2.5-linux-i686.egg/__init__.py", line 1, in <module>
    #
  File "build/bdist.linux-i686/egg/webob/datetime_utils.py", line 18, in <module>
  File "/usr/local/lib/python2.5/site-packages/WebOb-1.2b2-py2.5.egg/webob/compat.py", line 89
    return b''
             ^
SyntaxError: invalid syntax
</pre>

Maybe Pylons should use WebOb==1.1 in setup.py?

**Comment by bbangert** [comment]
Pylons works now with WebOb up to 1.4.
