### ISSUE TITLE
1.0.2 PyPi package is inconsistent

### ISSUE THREAD

**Issue by netme** [Pylons/pylons#32]
Seems to be that there is a small issue with a package on PyPi. 2 directories /test_files/sample_controllers/i18n and /test_files/sample_controllers/templates are missing. This leads to few failing tests when running `python setup.py test`.

Could you please fix the package?

**Comment by gward** [comment]
Here is how to reproduce this bug:
```
$ python setup.py -q sdist
$ tar -C /tmp -xf dist/Pylons-1.0.2.dev20150910.tar.gz
$ cd /tmp/Pylons-1.0.2.dev20150910
$ python setup.py test
```
Expected outcome: running tests from the tarball works.

Actual outcome: test failures, specifically:
```
[...]
tests.test_units.test_basic_app.TestJsonifyDecorator.test_detect_lang ... ERROR
tests.test_units.test_basic_app.TestJsonifyDecorator.test_eval ... ok
tests.test_units.test_basic_app.TestJsonifyDecorator.test_langs ... ERROR
tests.test_units.test_basic_app.TestJsonifyDecorator.test_no_lang ... ok
tests.test_units.test_basic_app.TestJsonifyDecorator.test_set_lang ... FAIL
tests.test_units.test_basic_app.TestJsonifyDecorator.test_set_lang_pylonscontext ... FAIL
[...]
======================================================================
ERROR: tests.test_units.test_basic_app.TestJsonifyDecorator.test_detect_lang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/Pylons-1.0.2.dev20150910/tests/test_units/test_basic_app.py", line 142, in test_detect_lang
    'Accept-Language':'fr;q=0.6, en;q=0.1, ja;q=0.3'})
  File "/usr/lib/python2.6/site-packages/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.6/site-packages/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/lib/python2.6/site-packages/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.6/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.6/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.6/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/tmp/Pylons-1.0.2.dev20150910/test_files/sample_controllers/controllers/i18nc.py", line 32, in i18n_index
    set_lang(request.languages)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/i18n/translation.py", line 178, in set_lang
    translator = _get_translator(lang, **kwargs)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/i18n/translation.py", line 166, in _get_translator
    raise LanguageError('IOError: %s' % ioe)
LanguageError: IOError: [Errno 2] No translation file found for domain: 'sample_controllers'
[...]
======================================================================
ERROR: tests.test_units.test_basic_app.TestJsonifyDecorator.test_langs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/Pylons-1.0.2.dev20150910/tests/test_units/test_basic_app.py", line 153, in test_langs
    'Accept-Language':'fr;q=0.6, en;q=0.1, ja;q=0.3'})
  File "/usr/lib/python2.6/site-packages/paste/fixture.py", line 208, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.6/site-packages/paste/fixture.py", line 389, in do_request
    **req.environ)
  File "/usr/lib/python2.6/site-packages/paste/wsgilib.py", line 343, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.6/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.6/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.6/site-packages/beaker/middleware.py", line 155, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.6/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/tmp/Pylons-1.0.2.dev20150910/test_files/sample_controllers/controllers/i18nc.py", line 44, in langs
    set_lang(request.languages)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/i18n/translation.py", line 178, in set_lang
    translator = _get_translator(lang, **kwargs)
  File "/tmp/Pylons-1.0.2.dev20150910/pylons/i18n/translation.py", line 166, in _get_translator
    raise LanguageError('IOError: %s' % ioe)
LanguageError: IOError: [Errno 2] No translation file found for domain: 'sample_controllers'
[...]
```
There are other failures, but they all boil down to the same thing.

**Comment by gward** [comment]
There's an easy workaround:
```
$ cd ~/src/pylons      # git working copy
$ rsync -va test_files/ /tmp/Pylons-1.0.2.dev20150910/test_files
$ cd /tmp/Pylons-1.0.2.dev20150910
$ python setup.py test
```
Now the tests pass. This suggests that the fix should be fairly easy.

**Comment by netme** [comment]
@gward thanks for checking it and fixing it! This is exactly the missing folder
