### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by opoplawski** [Pylons/pylons#36]
Trying to update the Fedora pylons package to 1.0.2 I'm getting:
~~~~~
ERROR: tests.test_units.test_basic_app.TestJsonifyDecorator.test_detect_lang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 142, in test_detect_lang
    'Accept-Language':'fr;q=0.6, en;q=0.1, ja;q=0.3'})
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 211, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 409, in do_request
    **req.environ)
  File "/usr/lib/python2.7/site-packages/paste/wsgilib.py", line 344, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers/i18nc.py", line 32, in i18n_index
    set_lang(request.languages)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 178, in set_lang
    translator = _get_translator(lang, **kwargs)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 166, in _get_translator
    raise LanguageError('IOError: %s' % ioe)
LanguageError: IOError: [Errno 2] No translation file found for domain: 'sample_controllers'
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /i18nc/i18n_index
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'i18n_index', 'controller': u'i18nc'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'i18nc'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.i18nc', class: 'I18NcController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'i18n_index' method to handle the request
pylons.controllers.core: DEBUG: Calling 'i18n_index' method with keyword args: **{}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: tests.test_units.test_basic_app.TestJsonifyDecorator.test_langs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 153, in test_langs
    'Accept-Language':'fr;q=0.6, en;q=0.1, ja;q=0.3'})
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 211, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 409, in do_request
    **req.environ)
  File "/usr/lib/python2.7/site-packages/paste/wsgilib.py", line 344, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers/i18nc.py", line 44, in langs
    set_lang(request.languages)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 178, in set_lang
    translator = _get_translator(lang, **kwargs)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 166, in _get_translator
    raise LanguageError('IOError: %s' % ioe)
LanguageError: IOError: [Errno 2] No translation file found for domain: 'sample_controllers'
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /i18nc/langs
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'langs', 'controller': u'i18nc'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'i18nc'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.i18nc', class: 'I18NcController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'langs' method to handle the request
pylons.controllers.core: DEBUG: Calling 'langs' method with keyword args: **{}
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: tests.test_units.test_i18n.TestI18N.test_noop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_i18n.py", line 51, in test_noop
    t = set_lang('fr', set_environ=False, pylons_config=lang_setup)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 178, in set_lang
    translator = _get_translator(lang, **kwargs)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/i18n/translation.py", line 166, in _get_translator
    raise LanguageError('IOError: %s' % ioe)
LanguageError: IOError: [Errno 2] No translation file found for domain: 'sample_controllers'

======================================================================
ERROR: tests.test_units.test_templating.TestTemplatingApp.test_template_cache
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_templating.py", line 77, in test_template_cache
    resp = self.app.get('/hello/time_template')
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 211, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 409, in do_request
    **req.environ)
  File "/usr/lib/python2.7/site-packages/paste/wsgilib.py", line 344, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers/hello.py", line 29, in time_template
    return render_mako('/time.html', cache_key='fred', cache_expire=20)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 244, in render_mako
    cache_type=cache_type, cache_expire=cache_expire)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 216, in cached_template
    expiretime=cache_expire)
  File "/usr/lib/python2.7/site-packages/beaker/cache.py", line 214, in get
    return self._get_value(key, **kw).get_value()
  File "/usr/lib/python2.7/site-packages/beaker/container.py", line 299, in get_value
    v = self.createfunc()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 239, in render_template
    template = globs['app_globals'].mako_lookup.get_template(template_name)
  File "/usr/lib/python2.7/site-packages/mako/lookup.py", line 259, in get_template
    "Cant locate template for uri %r" % uri)
TopLevelLookupException: Cant locate template for uri '/time.html'
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /hello/time_template
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'time_template', 'controller': u'hello'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'hello'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.hello', class: 'HelloController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'time_template' method to handle the request
pylons.controllers.core: DEBUG: Calling 'time_template' method with keyword args: **{}
beaker.container: DEBUG: data file /builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache/container_dbm/f/f2/f246b96c6e5bc523da041adfca8ffd3affc89fbd.dbm
beaker.container: DEBUG: opening dbm file /builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache/container_dbm/f/f2/f246b96c6e5bc523da041adfca8ffd3affc89fbd.dbm
beaker.container: DEBUG: closing dbm file /builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache/container_dbm/f/f2/f246b96c6e5bc523da041adfca8ffd3affc89fbd.dbm
beaker.container: DEBUG: lock_createfunc (waiting)
beaker.container: DEBUG: lock_createfunc (waited)
beaker.container: DEBUG: opening dbm file /builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache/container_dbm/f/f2/f246b96c6e5bc523da041adfca8ffd3affc89fbd.dbm
beaker.container: DEBUG: closing dbm file /builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache/container_dbm/f/f2/f246b96c6e5bc523da041adfca8ffd3affc89fbd.dbm
beaker.container: DEBUG: get_value creating new value
pylons.templating: DEBUG: Created render namespace with pylons vars: {'c': <pylons.util.ContextObj at 0x7f8f9ab45fd0>, 'ungettext': <function ungettext at 0x7f8f9f7b77d0>, 'url': <routes.util.URLGenerator object at 0x7f8f9aafc610>, 'h': None, 'request': <Request at 0x7f8f9aafc550 GET http://localhost/hello/time_template>, 'tmpl_context': <pylons.util.ContextObj at 0x7f8f9ab45fd0>, 'translator': <gettext.NullTranslations instance at 0x7f8f9ab04998>, 'session': {'_accessed_time': 1455422204.254712, '_creation_time': 1455422204.254712}, 'N_': <function gettext_noop at 0x7f8f9f7b7488>, 'app_globals': <tests.test_units.test_templating.AppGlobals object at 0x7f8f9aafcf10>, 'config': {'pylons.app_globals': <tests.test_units.test_templating.AppGlobals object at 0x7f8f9aafcf10>, 'pylons.errorware': {'from_address': 'pylons@yourapp.com', 'error_email': None, 'error_message': 'An internal server error occurred', 'smtp_server': 'localhost', 'error_log': None, 'error_subject_prefix': 'WebApp Error: ', 'debug': False}, 'pylons.paths': {'templates': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/templates', 'controllers': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers', 'root': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers'}, 'pylons.cache_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache', 'routes.map': <routes.mapper.Mapper object at 0x7f8f9aafce90>, 'pylons.h': None, 'pylons.package': 'sample_controllers', 'pylons.strict_tmpl_context': True, 'pylons.response_options': {'headers': {'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}, 'errors': 'strict', 'charset': 'utf-8', 'content_type': 'text/html'}, 'lang': None, 'global_conf': {'cache_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache'}, 'pylons.request_options': {'errors': 'replace', 'decode_param_names': False, 'charset': 'utf-8', 'language': 'en-us'}, 'beaker.cache.data_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache', 'pylons.environ_config': {'session': 'beaker.session', 'cache': 'beaker.cache'}, 'app_conf': {}, 'pylons.tmpl_context_attach_args': False, 'debug': False, 'beaker.session.data_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/sessions'}, 'response': <Response at 0x7f8f9aafc390 200 OK>, '_': <function ugettext at 0x7f8f9f7b75f0>}
beaker.container: DEBUG: released create lock
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: tests.test_units.test_templating.TestTemplatingApp.test_testvars
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_templating.py", line 73, in test_testvars
    resp = self.app.get('/hello/intro_template')
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 211, in get
    return self.do_request(req, status=status)
  File "/usr/lib/python2.7/site-packages/paste/fixture.py", line 409, in do_request
    **req.environ)
  File "/usr/lib/python2.7/site-packages/paste/wsgilib.py", line 344, in raw_interactive
    app_iter = application(basic_environ, start_response)
  File "/usr/lib/python2.7/site-packages/paste/lint.py", line 170, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/middleware.py", line 155, in __call__
    self.app, environ, catch_exc_info=True)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/util.py", line 50, in call_wsgi_application
    app_iter = application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 152, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/routes/middleware.py", line 136, in __call__
    response = self.app(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 103, in __call__
    response = self.dispatch(controller, environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 214, in __call__
    response = self._dispatch_call()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/controllers/core.py", line 57, in _perform_call
    return func(**args)
  File "/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers/hello.py", line 26, in intro_template
    return render_mako('/hello.html')
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 244, in render_mako
    cache_type=cache_type, cache_expire=cache_expire)
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 219, in cached_template
    return render_func()
  File "/builddir/build/BUILD/Pylons-1.0.2/pylons/templating.py", line 239, in render_template
    template = globs['app_globals'].mako_lookup.get_template(template_name)
  File "/usr/lib/python2.7/site-packages/mako/lookup.py", line 259, in get_template
    "Cant locate template for uri %r" % uri)
TopLevelLookupException: Cant locate template for uri '/hello.html'
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /hello/intro_template
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'intro_template', 'controller': u'hello'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'hello'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.hello', class: 'HelloController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'intro_template' method to handle the request
pylons.controllers.core: DEBUG: Calling 'intro_template' method with keyword args: **{}
pylons.templating: DEBUG: Created render namespace with pylons vars: {'c': <pylons.util.ContextObj at 0x7f8f9ab32ed0>, 'ungettext': <function ungettext at 0x7f8f9f7b77d0>, 'url': <routes.util.URLGenerator object at 0x7f8f9aafc090>, 'h': None, 'request': <Request at 0x7f8f9aafc0d0 GET http://localhost/hello/intro_template>, 'tmpl_context': <pylons.util.ContextObj at 0x7f8f9ab32ed0>, 'translator': <gettext.NullTranslations instance at 0x7f8f9aaf4758>, 'session': {'_accessed_time': 1455422204.279118, '_creation_time': 1455422204.279118}, 'N_': <function gettext_noop at 0x7f8f9f7b7488>, 'app_globals': <tests.test_units.test_templating.AppGlobals object at 0x7f8f9aafc390>, 'config': {'pylons.app_globals': <tests.test_units.test_templating.AppGlobals object at 0x7f8f9aafc390>, 'pylons.errorware': {'from_address': 'pylons@yourapp.com', 'error_email': None, 'error_message': 'An internal server error occurred', 'smtp_server': 'localhost', 'error_log': None, 'error_subject_prefix': 'WebApp Error: ', 'debug': False}, 'pylons.paths': {'templates': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/templates', 'controllers': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers/controllers', 'root': '/builddir/build/BUILD/Pylons-1.0.2/test_files/sample_controllers'}, 'pylons.cache_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache', 'routes.map': <routes.mapper.Mapper object at 0x7f8f9ab0e250>, 'pylons.h': None, 'pylons.package': 'sample_controllers', 'pylons.strict_tmpl_context': True, 'pylons.response_options': {'headers': {'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}, 'errors': 'strict', 'charset': 'utf-8', 'content_type': 'text/html'}, 'lang': None, 'global_conf': {'cache_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache'}, 'pylons.request_options': {'errors': 'replace', 'decode_param_names': False, 'charset': 'utf-8', 'language': 'en-us'}, 'beaker.cache.data_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/cache', 'pylons.environ_config': {'session': 'beaker.session', 'cache': 'beaker.cache'}, 'app_conf': {}, 'pylons.tmpl_context_attach_args': False, 'debug': False, 'beaker.session.data_dir': '/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/cache/sessions'}, 'response': <Response at 0x7f8f9ab32e10 200 OK>, '_': <function ugettext at 0x7f8f9f7b75f0>}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tests.test_units.test_basic_app.TestJsonifyDecorator.test_set_lang
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 129, in test_set_lang
    self._test_set_lang('set_lang')
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 136, in _test_set_lang
    assert u'\u8a00\u8a9e\u8a2d\u5b9a\u3092\u300cja\u300d\u306b\u5909\u66f4\u3057\u307e\u3057\u305f'.encode('utf-8') in response
AssertionError: 
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /i18nc/set_lang
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'set_lang', 'controller': u'i18nc'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'i18nc'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.i18nc', class: 'I18NcController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'set_lang' method to handle the request
pylons.controllers.core: DEBUG: Calling 'set_lang' method with keyword args: **{}
pylons.controllers.core: DEBUG: Controller returned a unicode string , writing it to pylons.response
pylons.controllers.core: DEBUG: Calling Response object to return WSGI data
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tests.test_units.test_basic_app.TestJsonifyDecorator.test_set_lang_pylonscontext
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 132, in test_set_lang_pylonscontext
    self._test_set_lang('set_lang_pylonscontext')
  File "/builddir/build/BUILD/Pylons-1.0.2/tests/test_units/test_basic_app.py", line 136, in _test_set_lang
    assert u'\u8a00\u8a9e\u8a2d\u5b9a\u3092\u300cja\u300d\u306b\u5909\u66f4\u3057\u307e\u3057\u305f'.encode('utf-8') in response
AssertionError: 
-------------------- >> begin captured logging << --------------------
pylons.configuration: DEBUG: Initializing configuration, package: 'sample_controllers'
routes.middleware: DEBUG: Initialized with method overriding = True, and path info altering = True
routes.middleware: DEBUG: Matched GET /i18nc/set_lang_pylonscontext
routes.middleware: DEBUG: Route path: '/{controller}/{action}', defaults: {}
routes.middleware: DEBUG: Match dict: {'action': u'set_lang_pylonscontext', 'controller': u'i18nc'}
pylons.wsgiapp: DEBUG: Setting up Pylons stacked object globals
pylons.wsgiapp: DEBUG: Setting up paste testing environment variables
pylons.wsgiapp: DEBUG: Resolved URL to controller: u'i18nc'
pylons.wsgiapp: DEBUG: Found controller, module: 'sample_controllers.controllers.i18nc', class: 'I18NcController'
pylons.wsgiapp: DEBUG: Controller appears to be a class, instantiating
pylons.wsgiapp: DEBUG: Calling controller class with WSGI interface
pylons.controllers.core: DEBUG: Looking for u'set_lang_pylonscontext' method to handle the request
pylons.controllers.core: DEBUG: Calling 'set_lang_pylonscontext' method with keyword args: **{'pylons': <pylons.util.PylonsContext object at 0x7f8f9b33dd50>}
pylons.controllers.core: DEBUG: Controller returned a unicode string , writing it to pylons.response
pylons.controllers.core: DEBUG: Calling Response object to return WSGI data
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 108 tests in 6.254s

FAILED (failures=2, errors=5, skipped=1)
~~~~~

**Comment by gustawdaniel** [comment]
+ Last commit (a year ago)
+ Last issue 2 years ago
+ Without support for python 3
+ (building failed) badge

Is this project still supported? Know anyone his status?

I found this tool because was mentioned in issue about synchronization of "watson" - cli for time logging  

> https://github.com/TailorDev/Watson/issues/40

and I checking if it is worthy to learn or use it.

**Comment by stevepiercy** [comment]
@gustawdaniel the [README.rst](https://github.com/Pylons/pylons#pylons) and (official website)[https://pylonsproject.org/about-pylons-framework.html] both explain its status.

**Comment by ergo** [comment]
Individual parts of pylons like webob, sqlalchemy, mako are getting updates. We still use it on python2.7 without issues.
Any new projects should be built using Pyramid instead.

**Comment by gustawdaniel** [comment]
@stevepiercy, @ergo thank you very much.

**Comment by mikeorr** [comment]
Pyramid is "Pylons 2.0". Pylons is in maintenance-only mode because there are still production sites using it. Bugs affecting those sites are fixed as needed. There are no plans to upgrade it to Python 3, not any decision on how long to support it given Python 2's end-of-life in 2020. My organization is trying to get its last remaining Pylons applications into something else this year; one will be Javascript, the other Pyramid.
